events{
    worker_connections 1024;
}

http{
    
    upstream backend {
        server server1:7000;
        server server2:7000;
        server server3:7000;
    }

    server{
        listen 80;

        server_name localhost;

        location / {
             proxy_pass http://backend;
        }
    }
}